# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21
parchment_mappings_version=2024.11.10

minecraft_version=1.21
minecraft_version_range=[1.21,1.22)
neo_version=21.0.167
loader_version_range=[1,)

mod_id=stepup
mod_name=StepUp
mod_license=MIT
mod_version=1.4.4+mc1.21
mod_group_id=com.nottoomanyitems
